preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  maven-local:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 1.9.22
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.27.0

libraries:
  com.squareup.okhttp3:
    okhttp:
      version: 4.12.0
  com.squareup:
    kotlinpoet:
      version: 1.16.0
    javapoet:
      version: 1.13.0
  net.lingala.zip4j:
    zip4j:
      version: 2.11.5